<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);TimerResolutionApp.Core\**\*;TimerResolutionApp.Tests\**\*</DefaultItemExcludes>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <StartupObject>TimerResolutionApp.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>TimerResolutionApp</AssemblyName>
    <RootNamespace>TimerResolutionApp</RootNamespace>
    <Version>1.5.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="TimerResolutionApp.Core\TimerResolutionApp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="app.ico" />
  </ItemGroup>
</Project>
